model: "../model/Qwen_Qwen3-0.6B-tuplecpt_1e-6_1-epoch"

train: true
data: "./data"

fine_tune_type: lora
adapter_path: "./adapters/Qwen_Qwen3-0.6B-tuplecpt_1e-6_1-epoch-SFT-lr_5e-4-ep_2"

optimizer: muon
seed: 42

num_layers: -1   # or full layer count if your mx-lm version needs an integer

batch_size: 4
grad_accumulation_steps: 16

# This refers to the batches processed. One epoch = 2115.
iters: 4230
learning_rate: 5e-5

max_seq_length: 512
grad_checkpoint: true # set false if memory allows and you want more speed

val_batches: 1

steps_per_report: 250
steps_per_eval: 10000
save_every: 10000

lora_parameters:
  keys:
    - self_attn.q_proj
    - self_attn.k_proj
    - self_attn.v_proj
    - self_attn.o_proj
  rank: 16
  scale: 32.0
  dropout: 0.05